apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: deploy-service
  title: Deploy Service
  description: Deploy a service to the server
spec:
  owner: team
  type: service
  parameters:
    - title: Select a Repository
      required: true
      properties:
        repo:
          type: string
          enum: ["repo1", "repo2"]
    - title: Select a Branch
      required: true
      properties:
        branch:
          type: string
          enum: ["main", "develop"]
    - title: Select an Environment
      required: true
      properties:
        environment:
          type: string
          enum: ["staging", "production"]
  steps:
    - id: deploy
      name: Deploying Service
      action: execute:remote
      input:
        url: "https://your-deployment-server.com/deploy"
        method: POST
        headers:
          Authorization: "Bearer YOUR_TOKEN"
        body:
          repository: ${{ parameters.repo }}
          branch: ${{ parameters.branch }}
          environment: ${{ parameters.environment }}
  output:
    links:
      - title: View Deployment Logs
        url: "https://your-deployment-logs.com"
